---

- name: Fail if not RHEL
  ansible.builtin.fail:
    msg: "This role is only supported on Red Hat Enterprise Linux"
  when: ansible_distribution != "RedHat"

- name: Register host to RHSM
  ansible.builtin.include_tasks:
    file: register.yml
  when: rhsm_action == 'register'

- name: Unregister host from RHSM
  ansible.builtin.include_tasks:
    file: unregister.yml
  when: rhsm_action == 'unregister'
